version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "pre-commit"
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "pytest*"
          - "pre-commit"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
