---
name: CI

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*.*.*"  # Tags are handled by the release workflow
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      job-type: lint
      python-version: '3.13'

  test-python-3-11:
    name: Test Python 3.11
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      job-type: test
      python-version: '3.11'

  test-python-3-12:
    name: Test Python 3.12
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      job-type: test
      python-version: '3.12'

  test-python-3-13:
    name: Test Python 3.13
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      job-type: test
      python-version: '3.13'
      upload-coverage: true

  coverage-badge:
    name: Update Coverage Badge
    needs: test-python-3-13
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      job-type: coverage-badge
    secrets:
      CICD_APP_ID: ${{ secrets.CICD_APP_ID }}
      CICD_APP_PRIVATE_KEY: ${{ secrets.CICD_APP_PRIVATE_KEY }}

  build:
    name: Build Package
    needs: [lint, test-python-3-11, test-python-3-12, test-python-3-13]
    if: github.event_name != 'pull_request'  # Skip build on PRs
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      job-type: build

  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [lint, test-python-3-11, test-python-3-12, test-python-3-13]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.CICD_APP_ID }}
          private-key: ${{ secrets.CICD_APP_PRIVATE_KEY }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: "${{ steps.generate_token.outputs.token }}"
