---
name: CI

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*.*.*"  # Tags are handled by the release workflow
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight for cleanup

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv venv
          . .venv/bin/activate
          uv sync --all-extras --dev

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: |
          . .venv/bin/activate
          uv run pre-commit run --show-diff-on-failure --all-files
        env:
          SKIP: "no-commit-to-branch"

  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv venv
          . .venv/bin/activate
          uv sync --all-extras --dev
          uv pip install pytest-cov

      - name: Run tests with coverage
        run: |
          . .venv/bin/activate
          uv run pytest --cov=invgen --cov-report=xml --cov-report=term tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
          verbose: true
          flags: python-${{ matrix.python-version }}

      - name: Generate coverage badge
        if: matrix.python-version == '3.13'
        run: |
          pip install genbadge[coverage]
          genbadge coverage -i coverage.xml -o coverage-badge.svg

      - name: Upload coverage badge artifact
        if: matrix.python-version == '3.13'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: coverage-badge.svg
          retention-days: 30

      - name: Upload coverage report artifact
        if: matrix.python-version == '3.13'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          retention-days: 7

  post-test:
    name: Post-Test Actions
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Build package
        run: |
          pip install uv
          uv venv
          . .venv/bin/activate
          uv build

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7

      - id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.CICD_APP_ID }}
          private-key: ${{ secrets.CICD_APP_PRIVATE_KEY }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: "${{ steps.generate_token.outputs.token }}"
