---
name: Pull Request

on:
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      job-type: lint
      python-version: '3.13'

  test-python-3-11:
    name: Test Python 3.11
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      job-type: test
      python-version: '3.11'

  test-python-3-12:
    name: Test Python 3.12
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      job-type: test
      python-version: '3.12'

  test-python-3-13:
    name: Test Python 3.13
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      job-type: test
      python-version: '3.13'
      upload-coverage: true
