---
name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test-python-3-11:
    name: Test Python 3.11
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      job-type: test
      python-version: '3.11'

  test-python-3-12:
    name: Test Python 3.12
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      job-type: test
      python-version: '3.12'

  test-python-3-13:
    name: Test Python 3.13
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      job-type: test
      python-version: '3.13'

  build:
    name: Build Package
    needs: [test-python-3-11, test-python-3-12, test-python-3-13]
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      job-type: build

  publish:
    name: Publish to PyPI
    needs: build
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set release env, replace 'v' in tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" | sed "s/v//g" >> $GITHUB_ENV

      - name: Replace version in pyproject.toml
        run: |
          sed -i 's/^version = "[^"]*"/version = "${{env.RELEASE_VERSION}}"/' pyproject.toml

      - name: Publish package
        run: |
          uv venv
          . .venv/bin/activate
          uv publish
